<CQLSH_PATH> <SCHEMA_HOST> <SCHEMA_PORT> -e"SOURCE '<SCHEMA_FOLDER>/<DDL_FILE>';"
<CQLSH_PATH> <SCHEMA_HOST> <SCHEMA_PORT> -e"SOURCE '<SCHEMA_FOLDER>/<SAI_DDL_FILE>';"
<CQLSH_PATH> <SEARCH_HOST> <SEARCH_PORT> -e"SOURCE '<SCHEMA_FOLDER>/<SEARCH_DDL_FILE>';"
<CQLSH_PATH> <SEARCH_HOST> <SEARCH_PORT> -e"SOURCE '<SCHEMA_FOLDER>/<SEARCH_INDEX_FILE>';"

#testing schemas
<CQLSH_PATH> <SEARCH_HOST> <SEARCH_PORT> -e"SOURCE '<SCHEMA_FOLDER>/<TEST_SCHEMA>';"
<CQLSH_PATH> <SCHEMA_HOST> <SCHEMA_PORT> -e"SOURCE '<SCHEMA_FOLDER>/<SEQ_NUM_SCHEMA>';"

