USE customer;
CREATE SEARCH INDEX IF NOT EXISTS ON cust_acct_v1;
CREATE SEARCH INDEX IF NOT EXISTS ON contact;
CREATE SEARCH INDEX IF NOT EXISTS ON cust_acct_v1;
CREATE SEARCH INDEX IF NOT EXISTS ON payment_info_v1;
CREATE SEARCH INDEX IF NOT EXISTS ON assoc_accounts_v1;

